name: example-generic-redis
version: 0.0.0
synopsis: Example Redis client using tower-hs generic middleware
license: MIT
license-file: ../../LICENSE

dependencies:
  - base >= 4.14 && < 5

executables:
  example-generic-redis:
    main: Main.hs
    source-dirs: .
    dependencies:
      - tower-hs
      - bytestring >= 0.11 && < 0.13
      - hedis >= 0.15 && < 0.16
      - text >= 2.0 && < 2.2
